build.gradle, src/main/java/org/checkerframework/checker/builder/TypesafeBuilderTransfer.java, src/test/java/tests/AutoValueTest.java, src/test/java/tests/BasicTest.java, tests/autovalue/Animal.java
Adds a test for AutoValue Builder code.
=> Add AutoValue builder test

src/main/java/org/checkerframework/checker/builder/TypesafeBuilderTransfer.java, tests/basic/Issue20.java
In addition to checking for null, I needed to check that there was a relevant annotation.
Fixes #20.
=> Fix NPE reported by msridhar

tests/basic/SimpleInferenceMerge.java
=> Add control flow merge test

typesafe-builder-checker/build.gradle, typesafe-builder-checker/src/main/java/org/checkerframework/checker/builder/TypesafeBuilderAnnotatedTypeFactory.java
By replacing the check for a specific annotation by classname to a check via a String.
Fixes #39
=> Remove runtime dependency on Lombok

object-construction-checker/src/main/java/org/checkerframework/checker/objectconstruction/ObjectConstructionAnnotatedTypeFactory.java, object-construction-checker/tests/autovalue/Animal.java
=> Handle AutoValue Optionals

object-construction-checker/build.gradle, object-construction-checker/src/main/java/org/checkerframework/checker/objectconstruction/ObjectConstructionAnnotatedTypeFactory.java, object-construction-qual/build.gradle, returnsrcvr-checker/build.gradle, returnsrcvr-qual/build.gradle
=> [WIP] Update to Checker Framework 2.10.0; fixes #66

build.gradle, object-construction-checker/build.gradle, object-construction-qual/build.gradle, returnsrcvr-checker/build.gradle, returnsrcvr-qual/build.gradle
Consolidate some version numbers in the top-level build file to make upgrading easier
=> Further cleanup of Gradle build files

object-construction-checker/build.gradle, returnsrcvr-checker/build.gradle
See [this issue on the Checker Framework template](https://github.com/typetools/templatefora-checker/issues/8).
This issue solves the same problem for our checker, whose build files also suffered from it.
=> Add support for incremental builds when test data changes

README-developers.md, RELEASING.md
=> Update build and release instructions

README.md
Mike pointed out that we didn't have good docs for the Lombok/AutoValue defaulting rules.
Mike, are these docs sufficient to help you understand what is going on? If not, what other information do you need?
Manu, have I gotten the AutoValue rules correct? Are there any caveats like those I added for Lombok at the end that I don't know about?
=> Documentation on Lombok/AutoValue defaulting

build.gradle
Checker Framework 3.1.1 has some improvements related to generics that make the output of this checker less noisy.
=> Update to Checker Framework 3.1.1

object-construction-checker/src/main/java/org/checkerframework/checker/objectconstruction/ObjectConstructionAnnotatedTypeFactory.java, object-construction-checker/src/main/java/org/checkerframework/checker/objectconstruction/framework/AutoValueSupport.java, object-construction-checker/tests/autovalue/SetInsideBuild.java, object-construction-checker/tests/autovalue/SetInsideBuildWithCM.java
it injects a @CalledMethods annotation for both autoBuild() and build() methods.
Fixes #129
=> Improved handling of AutoValue autoBuild() methods

README.md
Most users won't care, but anyone wanting to integrate this into a build system needs to know.
I also augmented the cf gradle plugin version to the latest, since I noticed it hadn't been updated in awhile.
=> Add note about lombok requirements

object-construction-checker/src/main/java/org/checkerframework/checker/objectconstruction/ObjectConstructionChecker.java, object-construction-checker/src/main/java/org/checkerframework/checker/objectconstruction/ObjectConstructionVisitor.java
=> Use new CF extension point to avoid needing to parse CM annotations for error reporting

build.gradle, object-construction-checker/src/main/java/org/checkerframework/checker/objectconstruction/ObjectConstructionChecker.java
Remove use of a newly-deprecated meta-annotation
=> Update to Checker Framework 3.5.0

must-call-checker/src/main/java/org/checkerframework/checker/mustcall/NoObligationStreams.astub, must-call-checker/src/main/java/org/checkerframework/checker/mustcall/Stream.astub, must-call-checker/tests/mustcall/SystemInOut.java
Would have prevented 2 FPs in Zookeeper.
=> Stubs for java.lang.System streams

object-construction-checker/src/main/java/org/checkerframework/checker/objectconstruction/MustCallInvokedChecker.java
Re-do of #244 now that #242 is merged
=> Add exception type in error message

must-call-checker/src/main/java/org/checkerframework/checker/mustcall/Stream.astub, must-call-checker/tests/mustcall/FileDescriptors.java, object-construction-checker/tests/socket/FileDescriptorTest.java
Replacement for #264 that's targeted at the correct branch.
=> Fixed stubs and new tests for FileDescriptor problem

must-call-checker/src/main/java/org/checkerframework/checker/mustcall/Stream.astub
https://docs.oracle.com/javase/7/docs/api/java/io/PushbackInputStream.html
=> stub for pushbackinputstream

object-construction-checker/src/main/java/org/checkerframework/checker/objectconstruction/MustCallInvokedChecker.java, object-construction-checker/tests/socket/ReassignmentWithMCC.java
This PR handles reassignments that the rhs is @MustCallChoice with the lhs.
=> reassignments with the same resource

object-construction-checker/src/main/java/org/checkerframework/checker/objectconstruction/MustCallInvokedChecker.java, object-construction-checker/src/main/java/org/checkerframework/checker/objectconstruction/ObjectConstructionChecker.java, object-construction-checker/src/test/java/tests/CountTest.java, object-construction-checker/tests/counter/CounterTest.java
This PR handles the negative count issue.
=> Counting must-call obligations

must-call-checker/src/main/java/org/checkerframework/checker/mustcall/NotOwning.astub
=> add annotation for isOpen

object-construction-checker/src/main/java/org/checkerframework/checker/objectconstruction/MustCallInvokedChecker.java, object-construction-checker/tests/socket/MCCNotOwningField.java, object-construction-checker/tests/socket/MCCWithThis.java
=> no warning on MCC with this

must-call-checker/src/main/java/org/checkerframework/checker/mustcall/MustCallChecker.java, must-call-checker/src/main/java/org/checkerframework/checker/mustcall/MustCallNoAccumulationFramesChecker.java, must-call-checker/src/main/java/org/checkerframework/checker/mustcall/MustCallTransfer.java, must-call-checker/src/main/java/org/checkerframework/checker/mustcall/NotOwning.astub, must-call-checker/src/main/java/org/checkerframework/checker/mustcall/Socket.astub, must-call-checker/src/main/java/org/checkerframework/checker/mustcall/SocketAccumulationFrames.astub, object-construction-checker/src/main/java/org/checkerframework/checker/objectconstruction/MustCallInvokedChecker.java, object-construction-checker/src/main/java/org/checkerframework/checker/objectconstruction/ObjectConstructionAnnotatedTypeFactory.java, object-construction-checker/src/main/java/org/checkerframework/checker/objectconstruction/ObjectConstructionChecker.java, object-construction-checker/src/main/java/org/checkerframework/checker/objectconstruction/ObjectConstructionTransfer.java, object-construction-checker/src/test/java/tests/NoAccumulationFramesTest.java, object-construction-checker/tests/noaccumulationframes/ConnectingServerSockets.java, object-construction-checker/tests/noaccumulationframes/ConnectingSockets.java, object-construction-checker/tests/noaccumulationframes/ResetMustCallSimpler.java, object-construction-checker/tests/noaccumulationframes/SocketContainer.java
This was a bit more convoluted than I would have liked, since we load stub files via the `@StubFiles` annotation. This approach works, but it's kinda gross ¯\_(ツ)_/¯
=> Feature flag for ResetMustCall

object-construction-checker/src/main/java/org/checkerframework/checker/objectconstruction/ObjectConstructionChecker.java
I'm getting deja vu, since this definitely happened last time I did this too and I just forgot :(
=> make the count an error, so that maven doesn't eat it

must-call-checker/src/main/java/org/checkerframework/checker/mustcall/MustCallAnnotatedTypeFactory.java, must-call-checker/src/main/java/org/checkerframework/checker/mustcall/MustCallChecker.java, must-call-checker/src/main/java/org/checkerframework/checker/mustcall/MustCallVisitor.java, object-construction-checker/src/main/java/org/checkerframework/checker/objectconstruction/MustCallInvokedChecker.java, object-construction-checker/src/main/java/org/checkerframework/checker/objectconstruction/ObjectConstructionAnnotatedTypeFactory.java, object-construction-checker/src/main/java/org/checkerframework/checker/objectconstruction/ObjectConstructionChecker.java, object-construction-checker/src/test/java/tests/NoResourceAliasesTest.java, object-construction-checker/tests/noresourcealias/MustCallChoiceExamples.java, object-construction-checker/tests/noresourcealias/MustCallChoicePassthroughLocal.java
This was by far the easiest of these flags to implement. I'll run experiments with all three flags on Zookeeper this afternoon and put the results in the paper.
=> feature flag for MustCallChoice

experimental-machinery/ablation/ablation-instructions.txt, experimental-machinery/ablation/errors-without-custom-types.sh, experimental-machinery/ablation/run-always-call-on-zookeeper.sh, experimental-machinery/ablation/zookeeper-ablation.sh, experimental-machinery/case-studies/build-all-and-collect-timing-info.sh, experimental-machinery/case-studies/how-to-count-added-lines.txt, object-construction-checker/tests/socket/PaperExample.java
Mike suggested to me that we check in the scripts and instructions for computing the results in the paper, rather than sending them around in emails. Obviously we should do that, and I'm kicking myself for not doing it sooner.
So, I think this is all of the instructions/scripts that I've sent around in the past few days. This way we won't lose them.
=> experimental machinery

object-construction-checker/src/main/java/org/checkerframework/checker/objectconstruction/MustCallInvokedChecker.java, object-construction-checker/src/main/java/org/checkerframework/checker/objectconstruction/ObjectConstructionChecker.java
And don't use crazy Java streams either.
=> Improve required.method.not.called error message

object-construction-checker/src/main/java/org/checkerframework/checker/objectconstruction/MustCallInvokedChecker.java
An ExceptionBlock may throw an exception, but it does not necessarily do so.
=> The problem can be normal exit from an ExceptionBlock

build.gradle, object-construction-checker/tests/cve/Cve.java
this should fix CI, so don't merge until CI is green
=> update to cf release version 3.11.0

experimental-machinery/case-studies/running-experiments.txt, experimental-machinery/case-studies/setup.sh
@msridhar these notes should help you understand the scripts that we have available, which should help with re-checking each benchmark
=> notes about scripts, plus instructions for adding new benchmarks systematically

object-construction-checker/tests/mustcall/Enclosing.java
fixes #366 
(The fix was merged elsewhere, but there was no explicit test for that issue.)
=> Test for issue 366
