- src/main/java/org/checkerframework/checker/builder/TypesafeBuilderAnnotatedTypeFactory.java
- src/main/java/org/checkerframework/checker/builder/TypesafeBuilderTransfer.java
- tests/basic/SimpleFluentInference.java
In the presence of an @ReturnsReceiver annotation, the annotated type factory now infers @CalledMethods annotations for chained (aka fluent) builders.
This implementation is unsound unless the @ReturnsReceiver annotation is checked. In this version of the code, it is trusted; we plan to implement a check soon.
This fixes #2.
See discussion on an earlier version of this PR in #4.
> Add support for fluent builders in the presence of @ReturnsReceiver annotations

- build.gradle
This picks up the fix for typetools/checker-framework#2462, which makes browsing the source of the Checker Framework easier in an IDE.
> Bump to Checker Framework 2.8.1

- build.gradle
With this change you can run `./gradlew publishToMavenLocal` to push a snapshot build to the local Maven repository, which makes it easy to import the checker into other projects.
> Add maven-publish plugin

- build.gradle
- src/main/java/org/checkerframework/checker/builder/CalledMethodsPredicateEvaluator.java
- src/main/java/org/checkerframework/checker/builder/TypesafeBuilderAnnotatedTypeFactory.java
- src/main/java/org/checkerframework/checker/builder/TypesafeBuilderVisitor.java
- src/main/java/org/checkerframework/checker/builder/messages.properties
- src/main/java/org/checkerframework/checker/builder/qual/CalledMethods.java
- src/main/java/org/checkerframework/checker/builder/qual/CalledMethodsBottom.java
- src/main/java/org/checkerframework/checker/builder/qual/CalledMethodsPredicate.java
- src/main/java/org/checkerframework/checker/builder/qual/CalledMethodsTop.java
- src/test/java/tests/EC2Test.java
- stubs/DescribeImages.astub
- tests/basic/CmPredicate.java
- tests/basic/UnparseablePredicate.java
- tests/cve/Cve.java
- tests/cve/Cve2.java
This pull request adds support for a new annotation in the `@CalledMethods` type system: `@CalledMethodsPredicate`. This annotation exists to generically extend the possibly least upper bounds that are expressible in this type system by permitting disjunctions.
The motivation for this addition to the type system is that there are builders (and other kinds of situations) where we want to permit a few different _combinations_ of called methods. Take, for example, this example in `tests/cve/Cve.java`, which is an AWS API that is vulnerable to a so-called "AMI sniping" attack (which permits malicious code injection) if one of the logical parameters is specified without another. However, another safe set of calls uses a totally different parameter, and ignores the other two calls. The stub …
> Implementation of @CalledMethodsPredicate

- build.gradle
- src/main/java/org/checkerframework/checker/builder/CalledMethodsPredicateEvaluator.java
- src/main/java/org/checkerframework/checker/builder/TypesafeBuilderAnnotatedTypeFactory.java
- src/main/java/org/checkerframework/checker/builder/TypesafeBuilderVisitor.java
For evaluating `@CalledMethodsPredicate`. There should be no functional difference, but SPEL uses the Apache license, while Javaluator is LGPL3, which isn't really compatible with the license on this repository.
As a bonus, the code is simpler. There's a horrible hack in there because I'm terrible at regular expressions, but for now that should be okay. @martinschaef, you should be able to use this branch in your experiments.
> Replace Javaluator with SPEL

- build.gradle
- src/main/java/org/checkerframework/checker/builder/CalledMethodsPredicateEvaluator.java
- src/main/java/org/checkerframework/checker/builder/TypesafeBuilderAnnotatedTypeFactory.java
- src/main/java/org/checkerframework/checker/builder/TypesafeBuilderChecker.java
- src/main/java/org/checkerframework/checker/builder/TypesafeBuilderTransfer.java
- src/main/java/org/checkerframework/checker/builder/TypesafeBuilderVisitor.java
- src/main/java/org/checkerframework/checker/builder/qual/CalledMethods.java
- src/main/java/org/checkerframework/checker/builder/qual/CalledMethodsBottom.java
- src/main/java/org/checkerframework/checker/builder/qual/CalledMethodsPredicate.java
- src/main/java/org/checkerframework/checker/builder/qual/CalledMethodsTop.java
- src/main/java/org/checkerframework/checker/builder/qual/ReturnsReceiver.java
- src/test/java/tests/BasicTest.java
- src/test/java/tests/EC2Test.java
Via the [spotless](https://github.com/diffplug/spotless/tree/master/plugin-gradle#applying-to-java-source-google-java-format) plugin, using Google's Java format (which I am a fan of, and which is used by the Checker Framework).
I am merging this change without approval, assuming that it builds on Travis, because it is non-functional.
> Enforce style

- build.gradle
- stubs/DescribeImages.astub
- tests/cve/OnlyOwnersFalsePositive.java
- tests/cve/RequestCreatedInCall.java
- tests/cve/SimpleFalsePositive.java
Added some new test cases that are examples of false positives encountered while using the CVE stub to hunt for mis-uses of AWS APIs. All were attributable to the stub file being overly restrictive, which it was in two distinct ways:
* the stub file *required* programmers to call `withFilters` if they called `withOwners`. Some people might legitimately want to find all the AMIs belonging to an owner, so I eased that restriction.
* the stub file only included `@ReturnsReceiver` annotations on the versions of the `withX` methods that take a varargs array, and not the versions that take a collection, so calls to those versions of the methods were causing information to be lost.
> Fix some false positives in the CVE examples

- build.gradle
- src/main/java/org/checkerframework/checker/builder/TypesafeBuilderAnnotatedTypeFactory.java
- src/test/java/tests/AutoValueTest.java
- tests/autovalue/Animal.java
Support for inserting `@This` annotations for AutoValue Builders was added to the returns receiver checker in msridhar/returnsrecv-checker#1.  Building on that, this PR implements `@CalledMethods` insertion for AutoValue Builders.  With this change, the checker is able to check AutoValue Builder usage for correctness with no manual annotations required; see updates to the `Animal.java` test case.
> Implement @CalledMethods insertion for AutoValue Builders

- src/main/resources/META-INF/services/javax.annotation.processing.Processor
This will allow us to run the checker without adding a `-processor` flag, by just adding the jar to the processor path, leveraging processor auto-discovery.  This is important for running on projects that already use processor auto-discovery.
> Add manifest file for processor auto-discovery

- build.gradle
- src/main/java/org/checkerframework/checker/builder/qual/CalledMethodsBottom.java
Fix meta-annotations for compatibility.  Note that the tests will not pass until the returns-receiver checker is also updated; see msridhar/returnsrecv-checker#6.
> Update to Checker Framework 2.9.0

- src/main/java/org/checkerframework/checker/builder/TypesafeBuilderAnnotatedTypeFactory.java
- tests/autovalue/AnimalNoSet.java
- tests/autovalue/GetAndIs.java
- tests/autovalue/GetAnimal.java
1. Don't treat non-`abstract` methods as corresponding to required properties
2. Handle more sophisticated mappings between AutoValue method names and the corresponding Builder method names
> Fixes for AutoValue support

- .gitignore
- src/main/java/org/checkerframework/checker/builder/TypesafeBuilderAnnotatedTypeFactory.java
- tests/autovalue/Animal.java
Feature documented here:
https://github.com/google/auto/blob/master/value/userguide/builders-howto.md#to_builder
We handle as follows:
* Don't treat `toBuilder` as a regular property requiring a setter in the `Builder`
* Inject an annotation on the returned `Builder` from `toBuilder`, indicating that all required properties are already set.
> Handle AutoValue toBuilder method

- src/main/java/org/checkerframework/checker/builder/TypesafeBuilderAnnotatedTypeFactory.java
- tests/autovalue/Animal.java
Similar to msridhar/returnsrecv-checker#8.  With multiple rounds of annotation processing, we cannot rely on ASTs for all relevant code being present in all rounds.  This issue was exposed on a larger benchmark.  Fixing the issue exposes a bug in our AutoValue `toBuilder` support (we were not injecting annotations for the generated `toBuilder` implementation).  I have temporarily commented out that test so it can be fixed in a separate follow-up PR.
> Refactor code to not require trees

- src/main/java/org/checkerframework/checker/builder/TypesafeBuilderAnnotatedTypeFactory.java
- tests/autovalue/Animal.java
The generated code corresponding to `AutoValue.toBuilder` now type checks.  We had to inject a `@CalledMethods` annotation with all required setters in the following places:
1. On the return of the generated `toBuilder()` method
2. On the call of the `Builder` constructor within the generated `toBuilder()` method
This change required pulling several methods out of the type annotator so they could also be used by the tree annotator.  I handled the constructor call in the tree annotator since I got weird new errors when trying to annotate the constructor itself in the type annotator.
> Handle generated code for AutoValue toBuilder

- src/main/java/org/checkerframework/checker/builder/TypesafeBuilderAnnotatedTypeFactory.java
- tests/autovalue/IsPreserved.java
AutoValue may or may not strip 'is' and 'get' from property names and may or may not prefix the property name with 'set', depending on how the code is written.  Handle these cases more thoroughly and cleanly.
> Handle weird cases where 'is' and 'get' are part of property name

- build.gradle
This adds a separate artifact containing only the type annotations defined by the checker, following the same design style as the `checker.jar` vs `checker-qual.jar` difference in the main Checker Framework.
A separate artifact is needed because the annotations need to be on the actual classpath when compiling the program, but the checker (and its heavy-weight dependency on the Checker Framework) does not.
This pull request depends on [#11](https://github.com/msridhar/returnsrecv-checker/pull/11) in the Returns Receiver Checker, because it automatically adds the new qual artifact of that checker as a dependency to this qual artifact - which means that a user who wants to use this checker only needs to take the one dependency.
> Add separate qual artifact

- src/main/java/org/checkerframework/checker/builder/TypesafeBuilderAnnotatedTypeFactory.java
- tests/autovalue/NonAVBuilder.java
Previously, we would try to handle non-abstract `toBuilder` methods that were unrelated to AutoValue, causing a crash.
> Check that AutoValue toBuilder() method is abstract

- build.gradle
- src/main/java/org/checkerframework/checker/builder/TypesafeBuilderAnnotatedTypeFactory.java
- tests/autovalue/GuavaImmutable.java
- tests/autovalue/GuavaImmutablePropBuilder.java
AutoValue has special handling of properties with a Guava Immutable type.  For such a property `foo`, if the AutoValue Builder has a method `fooBuilder()`, then the Builder automatically populates the property with an empty collection if `fooBuilder()` is never called.  So in such cases, don't treat `foo` as a required property.
> Fix handling of Guava Immutable types

- typesafe-builder-checker/src/main/java/org/checkerframework/checker/builder/TypesafeBuilderAnnotatedTypeFactory.java
- typesafe-builder-checker/src/main/java/org/checkerframework/checker/builder/TypesafeBuilderTransfer.java
- typesafe-builder-checker/tests/autovalue/Animal.java
Two changes:
* move the code for checking whether a `MethodInvocationTree` returns an `@This` result into its own method, so I can call it from the Transfer class, and
* fix the nested receiver bug reported in #42 by looping over the receivers of `MethodInvocationNode`s that all have `@This` annotations on their return types until I either reach a call to a method that doesn't return `@This` or a node that isn't a method
Fixes #42.
> Fix nested receiver bug

- README-LOMBOK.md
- README.md
- object-construction-checker/src/main/java/org/checkerframework/checker/builder/ObjectConstructionAnnotatedTypeFactory.java
The package is still `builder` (that is, `org.checkerframework.checker.builder`).
Is it intentional that it was not renamed?
> Rename "typesafe builder checker" to "object construction checker"

- object-construction-checker/src/main/java/org/checkerframework/checker/objectconstruction/ObjectConstructionAnnotatedTypeFactory.java
Lombok permits the user to manually write parts of a builder, and generate the rest. When that happens, Lombok doesn't place the `@Generated` annotation on the builder itself, but on the generated methods. This PR adds support for builders in that pattern.
> Recognize Lombok builders that have been partially written manually

- README.md
- object-construction-checker/src/main/java/org/checkerframework/checker/objectconstruction/ObjectConstructionAnnotatedTypeFactory.java
- object-construction-checker/tests/basic/Not.java
- object-construction-checker/tests/basic/Xor.java
Supporting unsound bug-finding was surprisingly easy: the boolean expression parser we were using already supports the not operator, so the only code change I had to make was to changing the `isSubtype` implementation so top is not always assumed to be un-assignable: `@CalledMethodsUnknown` is a subtype of `@CalledMethodsPredicate("!foo")`, for example.
I also added two test cases. XOR isn't natively supported by our parser, but it's easily representable as `(a || b) && !(a && b)`, so that's not too bad.
I also added a note to the README that using the not operator in `CalledMethodsPredicate` makes the checker unsound.
> Support for NOT operation in @CalledMethodPredicate

- object-construction-checker/build.gradle
This is useful for copy-pasting the path for use with https://github.com/kelloggm/do-like-javac
> Add task to print classpath

- object-construction-checker/src/main/java/org/checkerframework/checker/objectconstruction/ObjectConstructionAnnotatedTypeFactory.java
It seems that when I added support for Lombok `toBuilder` code I neglected to change the method called to produce the `@CalledMethods` annotation. This PR fixes that oversight.
> Correct dispatching problem in toBuilder handling

- returnsrcvr-checker/src/main/java/org/checkerframework/checker/returnsrcvr/ReturnsRcvrVisitor.java
- returnsrcvr-checker/src/test/java/tests/AllSystemsTest.java
- returnsrcvr-checker/tests/returnsrcvr/SimpleTest.java
A method declaration like `SimpleTest.@This I setBar()` should be allowed but before we were incorrectly reporting `invalid.this.location`.
Also, separate out `AllSystemsTests` to allow for running the simple returns receiver tests faster.
> Allow @This on qualified return type

- README-LOMBOK.md
Please also ensure that the `delombok` directory is (recursively) read-only, to prevent unintended edits.  That change should perhaps be in `checkerframework-gradle-plugin/src/main/groovy/org/checkerframework/gradle/plugin/CheckerFrameworkPlugin.groovy`.
> Don't edit the files in the error messages

- object-construction-checker/tests/basic/Generics.java
- object-construction-qual/src/main/java/org/checkerframework/checker/objectconstruction/qual/CalledMethodsTop.java
Without the `@DefaultFor` meta-annotation on `@CalledMethodsTop` we get an inscrutable `return.type.incompatible` error for the new `Generics` test.  We ran into a similar issue with the returns receiver checker, and I stole the solution from there.
> Add test cases for generics support

- object-construction-checker/src/main/java/org/checkerframework/checker/objectconstruction/ObjectConstructionAnnotatedTypeFactory.java
- object-construction-checker/tests/autovalue/NonBuildName.java
The build method for an AutoValue Builder need not be named `build`: https://github.com/google/auto/blob/master/value/userguide/builders-howto.md#build_names
So we now match the build method based on type, not name.
> Handle build method not named build() for AutoValue

- object-construction-checker/src/main/java/org/checkerframework/checker/objectconstruction/ObjectConstructionAnnotatedTypeFactory.java
- object-construction-checker/tests/autovalue/Validation.java
Sometimes AutoValue Builders have a non-abstract `build` method that does some validation, delegating to some other abstract method (usually named `autoBuild`) for the generated build logic.  We should only add a `@CalledMethods` annotation on the abstract method.
> Ensure AutoValue build method is abstract

- object-construction-checker/src/main/java/org/checkerframework/checker/objectconstruction/ObjectConstructionAnnotatedTypeFactory.java
- object-construction-checker/tests/autovalue/Inheritance.java
See the new `Inheritance` test case.  Before, we would not consider inherited abstract methods when determining required properties or potential setters in a Builder class.  To fix, we now look at abstract methods in all supertypes of `@AutoValue` and `@AutoValue.Builder` classes.
> Properly handle inherited methods for AutoValue and AutoValue Builder types

- object-construction-checker/src/main/java/org/checkerframework/checker/objectconstruction/ObjectConstructionAnnotatedTypeFactory.java
- object-construction-checker/tests/autovalue/Inheritance.java
When supporting inherited AutoValue methods we neglected to handle the case where the AutoValue type itself (or a supertype) provides a concrete implementation for a method.  We should exclude such cases as AutoValue will not generate code for such methods.
> Handle overridden abstract methods for AutoValue types

- object-construction-checker/src/main/java/org/checkerframework/checker/objectconstruction/ObjectConstructionChecker.java
- object-construction-checker/tests/autovalue/SetInsideBuild.java
I was stripping quotes from around required methods, but not actual methods, so the String comparison didn't work.
Fixes #99.
The new test case is the one from #99; it doesn't fail before this, since exact error messages aren't checked, but I figured there was no harm in including it. I tested that the new error messages are right by manually inspecting the output.
> Fix error message parsing bug

- object-construction-checker/src/main/java/org/checkerframework/checker/objectconstruction/ObjectConstructionAnnotatedTypeFactory.java
- object-construction-checker/stubs/DescribeImages.astub
- object-construction-checker/tests/cve/Cve.java
- object-construction-checker/tests/cve/Cve2.java
- object-construction-checker/tests/cve/MorePreciseFilters.java
- object-construction-checker/tests/cve/SpecialNames.java
This PR improves the precision of the `useValueChecker` option when used for AMI sniping detection. In particular, it makes the following improvements, each of which is based on a real false positive we have encountered:
* add `setExecutableUsers` and `withExecutableUsers` to the whitelist in the stub file
* add three new permitted filters: `image-id`, `owner-alias`, `owner-id`
* treat calls to `withName` as the same as using the filter constructor
* introspect into calls to `Collections.singletonList` and examine their arguments
> Improve precision of Value Checker enabled AMI sniping mode

- object-construction-checker/build.gradle
- object-construction-checker/src/main/java/org/checkerframework/checker/objectconstruction/ObjectConstructionAnnotatedTypeFactory.java
- object-construction-checker/tests/autovalue/FooParcelable.java
- object-construction-checker/tests/autovalue/Parcel.java
- object-construction-checker/tests/autovalue/Parcelable.java
Before, we would fail with a `RuntimeException` if we couldn't match what we thought was an AutoValue property to a corresponding setter in the builder.  But, we don't currently handle AutoValue extension (see #110), and adding full and proper handling will be pretty non-trivial.  So, instead of failing for these cases, just tolerate them.
Add a test case using the AutoValue Parcel extension to expose the problem, along with some stub Android classes so we don't need to pull in a full Android dependence.
> Don't fail when we can't find an AutoValue Builder setter method

- object-construction-checker/src/main/java/org/checkerframework/checker/objectconstruction/ObjectConstructionAnnotatedTypeFactory.java
- returnsrcvr-checker/src/main/java/org/checkerframework/checker/returnsrcvr/ReturnsRcvrAnnotatedTypeFactory.java
Workaround for typetools/checker-framework#2893.  In some cases we have seen that the code to load qualifiers using reflection does not work, so list them explicitly as a fallback.
> Load qualifiers for type systems explicitly

- object-construction-checker/src/main/resources/META-INF/services/javax.annotation.processing.Processor
This reverts #105.  Upon further thought, it seems best to keep this auto-dismanifest with the checker as long as it is living as its own artifact.  It would only cause a problem if someone included the checker in their build / processor path but didn't want to run it, and that scenario seems unlikely.  In #105 we discussed keeping the manifest in a separate artifact, but that seems like unnecessary complexity at this point.
> Re-add auto-discovery manifest file

- object-construction-checker/src/main/java/org/checkerframework/checker/objectconstruction/ObjectConstructionAnnotatedTypeFactory.java
- object-construction-checker/tests/basic/CmPredicate.java
I think I did this when I ran the original set of AMI sniping experiments last June, but never committed it (for some reason?). This modifies the tool to match the paper, which I must have written remembering this change (but not that I'd failed to commit it!):
> @CalledMethodsPredicate(P) ⊑ @CalledMethodsPredicate(P)
> Return true: every type is ⊑ itself.
> add *very* simple subtyping check for pairs of @CalledMethodsPredicate annotations

- object-construction-checker/src/main/java/org/checkerframework/checker/objectconstruction/ObjectConstructionAnnotatedTypeFactory.java
- object-construction-checker/tests/basic/Generics.java
Since the type qualifier of a generic type parameter should nearly always be `@CalledMethodsTop`, bias type inference in that direction by overriding `getDummyAssignedTo()`.  See additional generics test for a case where this change matters, and previously we would get a spurious error due to inferring a too-specific type.  See also typetools/checker-framework#2686
> Implement getDummyAssignedTo for better generic type inference

- returnsrcvr-checker/src/main/java/org/checkerframework/checker/returnsrcvr/ReturnsRcvrVisitor.java
- returnsrcvr-checker/tests/returnsrcvr/GenericReturn.java
We have a real-world example involving generics where we need to write `@This` in a typecast to get the code to type check.  A reduced test case is included.
> Allow @This annotation in cast expressions

- object-construction-checker/src/main/java/org/checkerframework/checker/objectconstruction/CalledMethodsPredicateEvaluator.java
- object-construction-checker/src/main/java/org/checkerframework/checker/objectconstruction/ObjectConstructionAnnotatedTypeFactory.java
- object-construction-checker/src/main/java/org/checkerframework/checker/objectconstruction/ObjectConstructionVisitor.java
This enables elimination of a copy operation in `ObjectConstructionAnnotatedTypeFactory.java`.
> Broaden type of argument to CalledMethodsPredicateEvaluator

- object-construction-checker/src/main/java/org/checkerframework/checker/objectconstruction/ObjectConstructionAnnotatedTypeFactory.java
- object-construction-checker/src/main/java/org/checkerframework/checker/objectconstruction/ObjectConstructionChecker.java
- object-construction-checker/tests/lombok/CheckerFrameworkBuilder.java
- object-construction-checker/tests/lombok/OldInherited.java
- object-construction-qual/src/main/java/org/checkerframework/checker/builder/qual/CalledMethods.java
- object-construction-qual/src/main/java/org/checkerframework/checker/builder/qual/NotCalledMethods.java
- returnsrcvr-qual/src/main/java/org/checkerframework/checker/builder/qual/ReturnsReceiver.java
I copied the delombok'd test code directly from Lombok's source, so this should match exactly what they do.
The downside is that we have to go back to releasing annotations in the `org.checkerframework.checker.builder.qual` package, but I don't think that's a deal breaker. I considered marking them as deprecated, but that caused extra warnings when processing delombok'd code so I decided against it.
The annotations this adds support for are:
* `@CalledMethods` in the `builder.qual` namespace, which behaves identically to `@CalledMethods`
* `@NotCalledMethods`, which they (speculatively) generate, does nothing
* `@ReturnsReceiver` is trusted if it's found but no `@This` annotation is. This is the only one I'm a little worried about, but I think it's probably fine. The Javadoc on it makes …
> Alias old annotations to fully support Lombok's `checkerframework = true` option

- .dependabot/config.yml
so I'm not spammed with updates to the AWS SDK every day
> Add configuration to only run dependabot once a week

- object-construction-checker/src/main/java/org/checkerframework/checker/objectconstruction/ObjectConstructionChecker.java
- object-construction-checker/src/main/java/org/checkerframework/checker/objectconstruction/ObjectConstructionTransfer.java
- object-construction-checker/src/main/java/org/checkerframework/checker/objectconstruction/ObjectConstructionVisitor.java
- object-construction-checker/tests/basic/PostconditionVarArgs.java
- object-construction-qual/src/main/java/org/checkerframework/checker/objectconstruction/qual/EnsuresCalledMethodsVarArgs.java
Add an `@EnsuresCalledsMethodVarArgs` annotation for methods, indicating that certain methods are called on _all_ parameters passed in the varargs position to the annotated method.  For now, this annotation is unverified and we always issue a warning when it is used.  Add support for `@EnsuresCalledMethodsVarArgs` to the transfer function of the object construction checker.
> Add @EnsuresCalledMethodsVarArgs annotation

- object-construction-checker/src/main/java/org/checkerframework/checker/objectconstruction/ObjectConstructionAnnotatedTypeFactory.java
- object-construction-checker/tests/mustcall/MustCallNullStore.java
The crash showed up when checking Hadoop.  I think it's potentially an issue with Checker data flow.  For now, add a null check to work around it.  Also add a couple of optimizations.  The optimization to `propagate()` speeds up the worklist algorithm quite a bit in some cases.
> Fix a crash and add a couple optimizations

- object-construction-checker/src/main/java/org/checkerframework/checker/objectconstruction/MustCallInvokedChecker.java
- object-construction-checker/src/main/java/org/checkerframework/checker/objectconstruction/ObjectConstructionAnnotatedTypeFactory.java
- object-construction-checker/src/main/java/org/checkerframework/checker/objectconstruction/ObjectConstructionVisitor.java
- object-construction-checker/tests/mustcall/ACRegularExitPointTest.java
* Extract the worklist algorithm for ensuring `@MustCall` methods are invoked to a new class `MustCallInvokedChecker`
* Break the code down into smaller methods
* Unify handling of successors.  Before we had separate methods for handling exceptional vs. normal successors, which led to some ugliness and bugs.  We now have a `handleSuccessors()` method for uniformly handling successors.  This change allowed us to remove a hack that @kelloggm was concerned about where we would eagerly remove variables from the tracked set without consulting the `@CalledMethods` types.  There is one additional expected error in our unit tests (see `ACRegularExitPointTest`), as this change removes a bit of path sensitivity (which I don't think is relevant in practice).
Further cleanup is likely possible, and …
> Extract and refactor code that ensures @MustCall methods are invoked

- must-call-checker/src/main/java/org/checkerframework/checker/mustcall/MustCallAnnotatedTypeFactory.java
- must-call-checker/tests/mustcall/BinaryInputArchive.java
- must-call-checker/tests/mustcall/FieldInitializationWithGeneric.java
- must-call-checker/tests/mustcall/SimpleStreamExample.java
- must-call-checker/tests/mustcall/StringSort.java
- must-call-checker/tests/mustcall/TypeArgs.java
A PR comment on #207 suggested using a `SimpleAnnotatedTypeScanner` rather than manually replacing only the top-level annotation for non-owning method parameters. That was a mistake.
The original reason that any types were replaced was to avoid false positive warnings when ownership wasn't being transferred. Using a type scanner causes the replacement to happen throughout the whole type - that seems good, but actually is a serious problem because generics are invariant: `@MustCallUnknown List<@MustCallUnknown String>` is NOT a supertype of `@MustCall({}) List<@MustCall({}) String>`, which generates a different spurious false positive.
This PR fixes the implementation and adds some test cases based on FPs in Zookeeper that this problem caused to prevent its recurrence.
> Fix serious mistake in handling of generics

- object-construction-checker/src/main/java/org/checkerframework/checker/objectconstruction/MustCallInvokedChecker.java
- object-construction-checker/tests/mustcall/TwoConstructorsCloseable.java
Without this change an error like the following is issued at line 11 of the test case:
```
[ERROR] /scratch/kelloggm/zookeeper/zookeeper-server/src/main/java/org/apache/zookeeper/common/X509Util.java:[170,12] error: [required.method.not.called] @MustCall method(s) close,  for variable/expression not invoked.  The type of object is: void.  Reason for going out of scope: never assigned to a variable
```
This is pretty clearly a false positive. I found two of them in Zookeeper. That's not a lot, but the fix was easy so I went ahead and made it anyway.
I tested this on my own machine with CF 3.8.0-SNAPSHOT, built this morning.
> Fix multiple-constructor false positives

- must-call-checker/src/main/java/org/checkerframework/checker/mustcall/MustCallAnnotatedTypeFactory.java
- must-call-checker/tests/mustcall/LogTheSocket.java
- must-call-checker/tests/mustcall/NonOwningPolyInteraction.java
- must-call-checker/tests/mustcall/OwningParams.java
- must-call-checker/tests/mustcall/PolyTests.java
- must-call-checker/tests/mustcall/Subtype0.java
- must-call-checker/tests/mustcall/Subtyping.java
~~The implementation is kind of hacky and relies on there being no other identifiers in a method body with the same name as its parameters. I *think* the scoping rules make that true, but I'm not sure.~~
I tried a couple of ~~less hacky~~ _other_ ways to implement this, but they all failed. Here are the ones that were most promising:
* override `TypeAnnotator#visitExecutable` and `GenericAnnotatedTypeFactory#addComputedTypeAnnotations(Element, ...)`: also changes the types when the method is called, which causes lots of false positives.
* override `visitVariable` in a `TreeAnnotator`, and change the type of the variable (both in the caches and the parameter) if the variable being declared is a non-owning method parameter. Doesn't seem to do anything except cause polymorphic types to be …
> Treat non-owning method parameters as @MustCall({}) while typechecking the body of the method

- unconnected-socket-checker/src/main/java/org/checkerframework/checker/unconnectedsocket/UnconnectedSocketAnnotatedTypeFactory.java
- unconnected-socket-checker/src/main/java/org/checkerframework/checker/unconnectedsocket/UnconnectedSocketChecker.java
- unconnected-socket-checker/src/main/java/org/checkerframework/checker/unconnectedsocket/UnconnectedSocketVisitor.java
- unconnected-socket-checker/tests/unconnectedsocket/NullField.java
- unconnected-socket-qual/src/main/java/org/checkerframework/checker/unconnectedsocket/qual/PossiblyConnected.java
Avoids a lot of false positive warnings like the test below in real code (I ran this on Zookeeper and saw these).
> Do not treat null fields as @Unconnected

- object-construction-checker/src/main/java/org/checkerframework/checker/objectconstruction/MustCallInvokedChecker.java
- object-construction-checker/tests/socket/EnhancedFor.java
This prevents warnings from being issued in non-source locations, which are really hard to interpret. Without this, the new case case issues a `required.method.not.called` error for the entire class due to the foreach loop, which is useless to the user.
I don't think there are any generated elements that won't be assigned into a local variable, but I might not be remembering something.
> Handle non-source code differently when checking pseudo-assignments

- object-construction-checker/src/main/java/org/checkerframework/checker/objectconstruction/MustCallInvokedChecker.java
- object-construction-checker/tests/mustcall/ACRegularExitPointTest.java
At a high level, the handling is similar to type casts.  Handling ternary expressions on the RHS of an assignment to some local variable `x` requires some care.  If an operand is a method call, we can treat it as if it were just normally being assigned to `x`, since whenever that expression branch executes, the result of the call is assigned to `x`.  But if an operand is a local variable `y`, we should _not_ do ownership transfer, as that branch of the expression is only executed conditionally and it is possible that `y` is not copied to `x`.
There is also some refactored code to handle ternary expressions and casts nested within each other; deeply-nested casts led to false positives before.  See changes to `ACRegularExitPoint` for the new tests.
> Handle ternary expressions

- object-construction-checker/src/main/java/org/checkerframework/checker/objectconstruction/MustCallInvokedChecker.java
`SingleSuccessorBlock.getSuccessor()` has a `@Nullable` return value, so we need this check.  We observed NPEs when analyzing real code
> Add null check for successor block

- object-construction-checker/tests/socket/BindChannel.java
- object-construction-checker/tests/socket/ZookeeperReport6.java
At some point while Travis was down, our CI stopped passing because of these two tests, both of which are related to unconnected sockets.
> Fixes to tests to make CI pass on always-call-checker branch

- must-call-checker/src/main/java/org/checkerframework/checker/mustcall/MustCallAnnotatedTypeFactory.java
- must-call-checker/tests/mustcall/TryWithResourcesCrash.java
I spent a bit of time trying to figure out why `MustCallVisitor` was passing `null`, but didn't find anything wrong with what it's doing - it's just calling `getAnnotationInHierarchy` in the common assignment check on the types it was passed, which is returning null in this case.
I'm not sure if this might be indicative of a bug in the CF, but this solution handles the problem on our end and should allow us to avoid unnecessary crashes in our case study.
> fix crash in try-with-resources encountered by Narges in hfds

- must-call-checker/src/main/java/org/checkerframework/checker/mustcall/MustCallAnnotatedTypeFactory.java
- object-construction-checker/tests/mustcall/ZookeeperByteBufferInputStream.java
The code that issues this error is called every time that an element type is computed (which is at every use of the relevant class). In Zookeeper, a single class that should produce this error ended up issuing 291 errors, which is a bit too many :)
The test doesn't actually check that only one error is issued, because the test framework doesn't distinguish multiple errors. I could add a test that checks the exact output, but I don't think that's really necessary. I checked it by hand.
> Don't issue duplicate `inconsistent.mustcall.subtype` errors

- object-construction-checker/src/main/java/org/checkerframework/checker/objectconstruction/MustCallInvokedChecker.java
- object-construction-checker/src/main/java/org/checkerframework/checker/objectconstruction/ObjectConstructionAnnotatedTypeFactory.java
- object-construction-checker/tests/mustcall/ZookeeperTernaryCrash.java
Fix is easy, and the crash would be hard to repro, so this is just the fix. I can try to minimize the failure if we think it's critical to have a unit test. Stack trace started with:
```
Exception: java.util.NoSuchElementException: No value present; java.util.NoSuchElementExc\
eption: No value present
at java.util.Optional.get(Optional.java:135)
at org.checkerframework.checker.objectconstruction.ObjectConstructionAnnotatedTypeF\
actory.getMustCallValue(ObjectConstructionAnnotatedTypeFactory.java:113)
at org.checkerframework.checker.objectconstruction.MustCallInvokedChecker.checkMust\
Call(MustCallInvokedChecker.java:997)
at org.checkerframework.checker.objectconstruction.MustCallInvokedChecker.handleSuc\
cessorBlocks(MustCallInvokedChecker.java:898)
at …
```
> Fix crash in Zookeeper

- must-call-checker/src/main/java/org/checkerframework/checker/mustcall/MustCallAnnotatedTypeFactory.java
- object-construction-checker/src/main/java/org/checkerframework/checker/objectconstruction/MustCallInvokedChecker.java
- object-construction-checker/src/main/java/org/checkerframework/checker/objectconstruction/ObjectConstructionVisitor.java
- object-construction-checker/src/test/java/tests/MustCallOnlyJDKTest.java
- object-construction-checker/tests/mustcall-onlyjdk/OnlyJDK.java
My intuition this afternoon that we'd need to write code to make our checker respect `-AonlyUses=` was correct (even if I named this branch wrong...): our custom error reporting doesn't go through the common assignment check, which is where that functionality is implemented.
I tried using `-AonlyUses=^java\.` on Zookeeper, which only removed 7 errors - far too small - so I investigated a bit and discovered this issue. This change adds a simple test case that uses that exact option, too, for extra fun. I tried to be efficient with the placement of the check, but in most cases it was easier to place the check right at the point where the error will be issued. This code path is only used in error reporting, so the impact on perf should be minimal regardless.
I ran `./gradlew clean build` …
> Respect -AonlyUses

- must-call-checker/src/main/java/org/checkerframework/checker/mustcall/Socket.astub
This API is used by Zookeeper.
> permit socket factories to produce unconnected sockets

- must-call-checker/src/main/java/org/checkerframework/checker/mustcall/Socket.astub
based on the docs here: https://docs.oracle.com/en/java/javase/11/docs/api/java.base/javax/net/ssl/SSLSocketFactory.html#createSocket(java.net.Socket,java.io.InputStream,boolean)
These methods modify the options of the existing socket; they're not taking ownership but creating a resource alias/MCC situation.
> use MCC for SSLSocketFactory

- object-construction-checker/src/main/java/org/checkerframework/checker/objectconstruction/MustCallInvokedChecker.java
These show up in one place is Zookeeper, where the code divides by a non-zero constant and then casts the result to `int`.
> ignore some more exceptions, plus document our assumptions about ignored exceptions

- object-construction-checker/src/main/java/org/checkerframework/checker/objectconstruction/MustCallInvokedChecker.java
- object-construction-checker/tests/socket/MCCOwningField.java
Note that this makes us unable to verify closing a must-call field through its resource-aliases, but I've never seen that pattern in practice.
> don't warn on method invocations whose return types are MCC with owning fields

- must-call-checker/src/main/java/org/checkerframework/checker/mustcall/MustCallChecker.java
- must-call-checker/src/main/java/org/checkerframework/checker/mustcall/Reflection.astub
- must-call-checker/tests/mustcall/ClassForNameInit.java
- object-construction-checker/src/main/java/org/checkerframework/checker/objectconstruction/ObjectConstructionChecker.java
- object-construction-checker/src/main/java/org/checkerframework/checker/objectconstruction/Reflection.astub
as we discussed today, this is definitely the right choice from a usability standpoint, even though it is technically unsound
should be easy to turn off this kind of handling by removing the stub, if we wanted
> handle reflection unsoundly via stub file

- must-call-checker/src/main/java/org/checkerframework/checker/mustcall/MustCallTransfer.java
- must-call-qual/src/main/java/org/checkerframework/checker/mustcall/qual/ResetMustCall.java
- object-construction-checker/src/main/java/org/checkerframework/checker/objectconstruction/MustCallInvokedChecker.java
- object-construction-checker/src/main/java/org/checkerframework/checker/objectconstruction/ObjectConstructionAnnotatedTypeFactory.java
- object-construction-checker/src/main/java/org/checkerframework/checker/objectconstruction/ObjectConstructionTransfer.java
- object-construction-checker/tests/mustcall/ResetMustCallIndirect.java
- object-construction-checker/tests/mustcall/ResetMustCallRepeat.java
- object-construction-checker/tests/socket/BindChannel.java
This was a lot more invasive of a change than I'd expected, which is especially galling given that this will reduce the FP count by at most one on Zookeeper. Still, I think it's something we should have.
There is one visible behavior change: unparseable expressions that are the target of an RMC method are now also flagged as non-owning. I think that's fine, since we're issuing errors in those cases anyway. See e.g. the change in `BindChannel.java`.
> make reset must call repeatable

- object-construction-checker/src/main/java/org/checkerframework/checker/objectconstruction/MustCallInvokedChecker.java
- object-construction-checker/tests/socket/SocketContainer.java
- object-construction-checker/tests/socket/SocketContainer2.java
- object-construction-checker/tests/socket/SocketContainer3.java
This PR covers several false positive causes in Zookeeper, all of which are related to `@ResetMustCall`:
* Reset must call required on constructor (2)
* Reassignment of owning field to null required reset must call (2)
* Required method not called on rhs of initializer of owning field (2)
It leaves in place some "expected" errors in the new tests that I don't think we actually need. These are errors about "re-assignments" to fields that occur in the constructor. I think such a "re-"assignment is safe if:
1. the field is defined in the class (i.e. the field isn't defined in a superclass)
2. the initializer is either not present or a `null` literal
3. the constructor doesn't dispatch to another constructor that might set the field (i.e. there is no `this(...)` call at the start of the …
> Various fixes to ResetMustCall/constructors

- object-construction-checker/src/main/java/org/checkerframework/checker/objectconstruction/ObjectConstructionChecker.java
this is slightly an anti-pattern, since it doesn't use the localizable interface, but this is the only API we have that doesn't require a source location at which to print
running the tests also no longer prints the counts directly, since these messages are below the logging level used by the testing framework (because we use `-Anowarn` in our test runs)
> use compiler messaging interface to print counts instead of printf

- object-construction-checker/src/main/java/org/checkerframework/checker/objectconstruction/MustCallInvokedChecker.java
- object-construction-checker/tests/mustcall/ACExceptionalExitPointTest.java
when I reran on Zookeeper, there were a bunch of extra false positives because of the improved precision in the CFG that we merged upstream earlier today, because `RuntimeException` and `Error` weren't on the list of exceptions that are permitted.
> adapt to improved precision in CF CFG

- must-call-checker/src/main/java/org/checkerframework/checker/mustcall/MustCallAnnotatedTypeFactory.java
- must-call-checker/src/main/java/org/checkerframework/checker/mustcall/MustCallTransfer.java
- object-construction-checker/src/main/java/org/checkerframework/checker/objectconstruction/ObjectConstructionTransfer.java
also clean up some gross-ness in OC transfer that I noticed, because it was convenient to do so
> don't keep around the tempvar cache in the MC checker forever because performance hates that

- must-call-checker/src/main/java/org/checkerframework/checker/mustcall/MustCallVisitor.java
- object-construction-checker/tests/mustcall/ManualMustCallEmptyOnConstructor.java
- object-construction-checker/tests/socket/ZookeeperReport3.java
fixes #326 
I had expected the CF to just handle this (via the Must Call Checker), so I was surprised when the test I wrote didn't fail. The reason was that I had disabled the relevant checking in BaseTypeVisitor for the Must Call Checker, because it was overly conservative - it assumed that every constructor return needed to be top! That's clearly inconsistent with Must Call (or any bottom-default typechecker, for that matter).
Actually, the constructor return just needs to be a super type of the declared lower bound for the class. This PR implements that check for Must Call.
IMO this change should probably be upstreamed into the CF's `BaseTypeVisitor`, probably after 25 Feb
> enforce requirements on constructor return types

- must-call-checker/src/main/java/org/checkerframework/checker/mustcall/MustCallTypeValidator.java
- must-call-checker/src/main/java/org/checkerframework/checker/mustcall/MustCallVisitor.java
- object-construction-checker/src/main/java/org/checkerframework/checker/objectconstruction/MustCallInvokedChecker.java
- object-construction-checker/tests/mustcall/MustCallChoiceImplWrong1.java
- object-construction-checker/tests/mustcall/MustCallChoiceImplWrong2.java
- object-construction-checker/tests/mustcall/MustCallChoicePassthrough.java
- object-construction-checker/tests/mustcall/MustCallChoicePassthroughChain.java
- object-construction-checker/tests/mustcall/MustCallChoicePassthroughLocal.java
- object-construction-checker/tests/mustcall/MustCallChoicePassthroughThis.java
- object-construction-checker/tests/mustcall/MustCallChoicePassthroughWrong1.java
- object-construction-checker/tests/mustcall/MustCallChoicePassthroughWrong2.java
- object-construction-checker/tests/mustcall/MustCallChoicePassthroughWrong3.java
- object-construction-checker/tests/mustcall/MustCallChoicePassthroughWrong4.java
This was...much easier than I had expected. I was able to re-use the machinery we built for owning fields, for the most part - once an MCC thing is assigned to an owning field, we're okay since our rules for those are sound.
There are basically two changes to MCIC:
* an `@MustCallChoice` parameter is now owning in its own method. This means that the usual ways to get rid of an obligation are allowed: you can close it, pass it to another owning method, assign it to an owning field, whatever
* there's an extra way to get rid of MCC obligations: you can pass it to another MCC constructor
I also had to modify the Must Call Checker so that it doesn't complain about poly annotations on types that are lowerbounded by `@MustCall("close")` (or similar), when the actual annotation is MCC. I think …
> Verify mcc

- must-call-checker/src/main/java/org/checkerframework/checker/mustcall/MustCallTransfer.java
- object-construction-checker/src/main/java/org/checkerframework/checker/objectconstruction/MustCallInvokedChecker.java
- object-construction-checker/tests/socket/BindChannel.java
- object-construction-checker/tests/socket/RMCInSubtype.java
- object-construction-checker/tests/socket/UnconnectedSocketAlias.java
This did change where one error was issued in `BindChannel.java`, which seems to be the test case that changes the most. I think that's fine. The reason is that there's a two-alias set in defs before `bind` is called containing both locals, but after there's only the one-alias set containing the second local (so the error is issued at the second local instead of the first).
I believe that this aligns the implementation with what you were describing for the paper, for the most part - there's still the split between the MCC and MCIC, but that's probably okay.
I did keep the owning logic in place, so reset.not.owning errors do still get issued. The basic premise of the owning logic is that there has to be something which takes ownership of the result. I think we only track must-alias for …
> fix RMC soundness bug

- object-construction-checker/src/main/java/org/checkerframework/checker/objectconstruction/MustCallInvokedChecker.java
- object-construction-checker/tests/counter/CounterTest.java
I also removed the cache of things that we've already counted, because with it there I couldn't get the numbers on the Counter Test to be correct.
> make countMustCall only count java* types

- object-construction-checker/src/main/java/org/checkerframework/checker/objectconstruction/ObjectConstructionChecker.java
- object-construction-checker/tests/counter/CounterTest.java
Narges noticed that my recent PR #336 didn't also update the computation of the `numFailedMustCall` field, so the results for that were garbage. This should fix it.
> don't count warnings about non-JDK classes when computing the number of failed MCs

- object-construction-checker/src/main/java/org/checkerframework/checker/objectconstruction/MustCallInvokedChecker.java
This is necessary in order to use the latest Checker Framework.
Once this is merged, then you must do
```cd $CHECKERFRAMEWORK && ./gradlew publishToMavenLocal```
before compiling this reporitory.
> Adapt to Checker Framework changes

- must-call-qual/src/main/java/org/checkerframework/checker/mustcall/qual/MustCallAlias.java
This is necessary for use with JDK 8.  (I don't know why.)
I have confirmed via testing that this works on JDK 8 whereas without the patch it does not.
After this is merged, Manu will need to make another release.
> Change `@Target` annotation on MustCallAlias

- object-construction-checker/build.gradle
We don't need these dependencies anymore as the functionality is implemented within the Checker Framework.
> Remove unnecessary deps

- must-call-checker/README.md
- must-call-checker/tests/mustcall/PlumeUtilRequiredAnnotations.java
- must-call-qual/src/main/java/org/checkerframework/checker/mustcall/qual/MustCall.java
Making `@MustCall` the default for `IMPLICIT_UPPER_BOUND` definitely reduces annotation burden in my case studies (and might do so for other case studies).
I'm not sure whether making it the default for `IMPLICIT_LOWER_BOUND` is desirable.
> Explain false positives due to implicit vs explicit bounds

- object-construction-checker/src/main/java/org/checkerframework/checker/objectconstruction/MustCallInvokedChecker.java
- object-construction-checker/tests/mustcall/MustCallAliasOwningField.java
See the new test.  Before, we would report a false positive warning when creating a must-call alias with a field.  Since we handle `@Owning` fields completely separately, there is no need to track the result of a call when its `@MustCallAlias` parameter is the result of a field read.
Eventually, it may be cleaner to find a way to ignore field reads in one place, rather than adding special checks in multiple places.  But that would take more thought.
> Fix false positive when creating a must-call alias with a field

- build.gradle
- must-call-checker/src/main/java/org/checkerframework/checker/mustcall/MustCallAnnotatedTypeFactory.java
- must-call-checker/src/main/java/org/checkerframework/checker/mustcall/MustCallTransfer.java
- object-construction-checker/src/main/java/org/checkerframework/checker/objectconstruction/MustCallInvokedChecker.java
- object-construction-checker/src/main/java/org/checkerframework/checker/objectconstruction/ObjectConstructionAnnotatedTypeFactory.java
- object-construction-checker/src/main/java/org/checkerframework/checker/objectconstruction/ObjectConstructionTransfer.java
- object-construction-checker/src/main/java/org/checkerframework/checker/objectconstruction/ObjectConstructionVisitor.java
Sorry that there are some extraneous changes in the Must Call Checker itself (i.e. adding docs, etc) - I copied the versions of those files from my PR against the CF proper, so they follow its javadoc guidelines.
I left intact a few uses of deprecated `getElementValueArray` calls, to avoid duplicating code. We probably should remove these, but it's a pain, because the code is shared between two different checkers and their type factories are taken as parameters (i.e. as `GenericAnnotatedTypeFactory`) depending on which checker uses the (static) method. Both need to get the same element from several shared annotations, so to fix this we'd need to create a subclass of GATF for them both to extend that has `ExecutableElement` fields for each of the annotation elements that these methods need …
> update to Checker Framework version 3.12.0

- must-call-checker/src/main/java/org/checkerframework/checker/mustcall/MustCallTransfer.java
- object-construction-checker/src/main/java/org/checkerframework/checker/objectconstruction/MustCallInvokedChecker.java
- object-construction-checker/src/main/java/org/checkerframework/checker/objectconstruction/ObjectConstructionChecker.java
- object-construction-checker/src/main/java/org/checkerframework/checker/objectconstruction/ObjectConstructionVisitor.java
- object-construction-checker/tests/mustcall/COAnonymousClass.java
- object-construction-checker/tests/mustcall/CreatesObligationIndirect.java
- object-construction-checker/tests/mustcall/CreatesObligationInnerClass.java
- object-construction-checker/tests/mustcall/CreatesObligationOverride.java
- object-construction-checker/tests/mustcall/CreatesObligationOverride2.java
This change will, I hope, fix #368. It doesn't address the problem directly, because I realized that the real issue behind #368 is that `run()` is overridden to add an `@CreatesObligation` annotation, but it could be dynamically-dispatched to by an object of static type `Runnable` but that is dynamically the anonymous class we defined. This problem isn't unique to anonymous classes; you'll see in the test cases that I was able to trigger the unsoundness without needing one.
I'm not convinced that my solution is great: I've restricted the places where `@CreatesObligation` can be written by adding a new kind of error that's issued when a method with fewer `@CreatesObligation` targets is overridden by one with more. Note that because `@CreatesObligation` is inheritable, in practice this …
> require that creates obligation targets aren't added when overriding methods

- object-construction-checker/src/main/java/org/checkerframework/checker/objectconstruction/MustCallInvokedChecker.java
- object-construction-checker/tests/mustcall/ACRegularExitPointTest.java
- object-construction-checker/tests/mustcall/SelfAssign.java
This is a cleaner and more correct handling of ternary expressions in `MustCallInvokedChecker`.  In short, we now properly leverage the representation of ternary expressions in the Checker Framework CFG to handle each case separately.  See `SelfAssign.test1()` for a case we can handle now (based on real code in HBase) that we couldn't handle before.  This also re-uses the cleaned-up logic for assignments from #377.  I tried to add sufficient documentation to make the logic clear.
> Fixed handling of ternary expressions

- object-construction-checker/src/main/java/org/checkerframework/checker/objectconstruction/MustCallInvokedChecker.java
- object-construction-checker/tests/mustcall/SocketField.java
fixes #381. Previously, we got the called methods type from the store before the assignment node, which is after the RHS in the CFG (and therefore can have its store affected by side-effects from evaluating the RHS).
> When checking re-assignment to a field, get the called methods type from the store before evaluating the RHS

- experimental-machinery/ablation/run-always-call-on-plume-util.sh
I think for the purposes of an artifact / experiment scripts, we should always do a clean build of `plume-util`.  I observed in the Docker container that sometimes the compilation doesn't run at all when running `run-always-call-on-plume-util.sh` since it ran already, which is good for the development process but could be surprising to someone trying to run our experiment scripts.
> Clean builds for plume util
